#!/usr/bin/env python3
"""Unittests for harness_deploy.py (P2-1)."""

from __future__ import annotations

import json
import shutil
import sys
import tempfile
import unittest
from pathlib import Path


SCRIPTS_DIR = Path(__file__).resolve().parents[1]
SKILLS_ROOT = SCRIPTS_DIR.parent
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

import harness_deploy as hd  # noqa: E402


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _fixture_root(tmp: Path) -> Path:
    root = tmp / "core"
    _write(
        root / "shared" / "p0-trust.md",
        "## P0 执行可信度规则\n\n- rule one\n",
    )
    _write(
        root / "harness-demo" / "SKILL.md",
        """---
name: harness-demo
---
# Demo

## Workflow 概要

core workflow line

## 构建验证

old build section

<!-- @include shared/p0-trust.md -->
> 片段：[[shared/p0-trust.md|p0-trust]]
""",
    )
    _write(root / "README.md", "# core\n")
    return root


class IncludeExpansionTests(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = Path(tempfile.mkdtemp(prefix="deploy-include-"))
        self.root = _fixture_root(self.tmp)

    def tearDown(self) -> None:
        shutil.rmtree(self.tmp, ignore_errors=True)

    def test_build_expands_includes_and_removes_placeholders(self) -> None:
        out = self.tmp / "out"
        result = hd.cmd_build(self.root, out, None)
        self.assertTrue(result["ok"])
        skill = (out / "harness-demo" / "SKILL.md").read_text(encoding="utf-8")
        self.assertIn("rule one", skill)
        self.assertNotIn("@include shared/", skill)
        self.assertNotIn("片段：[[shared/", skill)
        self.assertIn("generated by harness_deploy.py", skill)


class OverlayAnchorTests(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = Path(tempfile.mkdtemp(prefix="deploy-overlay-"))
        self.root = _fixture_root(self.tmp)
        overlay = self.root / "overlays" / "java"
        _write(
            overlay / "harness-demo.overlay.md",
            """<!-- @override section:"构建验证" -->
## 构建验证

mvn compile -pl demo-module

<!-- @append-after section:"Workflow 概要" -->
### Java 增量编译

read build-profile.json
""",
        )
        _write(
            overlay / "harness-extra" / "SKILL.md",
            """---
name: harness-extra
---
# Extra Java Skill
""",
        )

    def tearDown(self) -> None:
        shutil.rmtree(self.tmp, ignore_errors=True)

    def test_build_applies_override_and_append(self) -> None:
        out = self.tmp / "out"
        result = hd.cmd_build(self.root, out, "java")
        skill = (out / "harness-demo" / "SKILL.md").read_text(encoding="utf-8")
        self.assertIn("mvn compile -pl demo-module", skill)
        self.assertNotIn("old build section", skill)
        self.assertIn("### Java 增量编译", skill)
        self.assertTrue((out / "harness-extra" / "SKILL.md").is_file())

    def test_build_fails_on_missing_anchor(self) -> None:
        bad = self.root / "overlays" / "java" / "harness-demo.overlay.md"
        bad.write_text(
            '<!-- @override section:"不存在的章节" -->\n## X\n',
            encoding="utf-8",
        )
        with self.assertRaises(KeyError):
            hd.cmd_build(self.root, self.tmp / "bad-out", "java")


class InstallDiffTests(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = Path(tempfile.mkdtemp(prefix="deploy-install-"))
        self.root = _fixture_root(self.tmp)
        self.out = self.tmp / "build-out"
        hd.cmd_build(self.root, self.out, None)
        self.project = self.tmp / "project"
        self.project.mkdir()

    def tearDown(self) -> None:
        shutil.rmtree(self.tmp, ignore_errors=True)

    def test_install_creates_backup(self) -> None:
        target = self.project / ".claude" / "skills"
        target.mkdir(parents=True)
        _write(target / "old.txt", "old\n")
        result = hd.cmd_install(self.out, self.project, target)
        self.assertTrue(result["ok"])
        self.assertIsNotNone(result["backup"])
        self.assertTrue(Path(result["backup"]).is_dir())
        self.assertTrue((target / "harness-demo" / "SKILL.md").is_file())

    def test_diff_detects_outdated_file(self) -> None:
        target = self.project / ".claude" / "skills"
        hd.cmd_install(self.out, self.project, target)
        skill = target / "harness-demo" / "SKILL.md"
        skill.write_text(skill.read_text(encoding="utf-8") + "\n# tampered\n", encoding="utf-8")
        diff = hd.cmd_diff(self.out, self.project, target)
        self.assertTrue(diff["stale"])
        self.assertIn("harness-demo/SKILL.md", diff["outdated"])

    def test_core_hash_covers_runtime_reference_files(self) -> None:
        _write(self.root / "harness-demo" / "reference.md", "first\n")
        first = hd.core_content_hash(self.root, None)
        _write(self.root / "harness-demo" / "reference.md", "second\n")
        self.assertNotEqual(first, hd.core_content_hash(self.root, None))

    def test_install_rejects_unmarked_source_without_touching_target(self) -> None:
        target = self.project / ".claude" / "skills"
        _write(target / "old.txt", "old\n")
        unmarked = self.tmp / "unmarked"
        _write(unmarked / "file.txt", "bad\n")
        with self.assertRaises(ValueError):
            hd.cmd_install(unmarked, self.project, target)
        self.assertEqual((target / "old.txt").read_text(encoding="utf-8"), "old\n")


class RealSkillsRootBuildTests(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = Path(tempfile.mkdtemp(prefix="deploy-real-"))
        self.out = self.tmp / "out"

    def tearDown(self) -> None:
        shutil.rmtree(self.tmp, ignore_errors=True)

    @unittest.skipUnless(SKILLS_ROOT.is_dir(), "skills root missing")
    def test_build_generic_skills_root(self) -> None:
        result = hd.cmd_build(SKILLS_ROOT, self.out, None)
        self.assertTrue(result["ok"])
        self.assertGreaterEqual(len(result["processedSkills"]), 10)
        for rel in result["processedSkills"]:
            body = (self.out / rel).read_text(encoding="utf-8")
            self.assertNotIn("@include shared/", body)


class DeploySafetyReproTests(unittest.TestCase):
    """Task 5 (REMEDIATION-DESIGN §7): path safety, atomic staging swap,
    reproducible builds, runtime allowlist, section-id anchors."""

    def setUp(self) -> None:
        self.tmp = Path(tempfile.mkdtemp(prefix="deploy-safety-"))

    def tearDown(self) -> None:
        shutil.rmtree(self.tmp, ignore_errors=True)

    def test_build_refuses_out_equal_to_source(self) -> None:
        root = _fixture_root(self.tmp)
        with self.assertRaises(ValueError):
            hd.cmd_build(root, root, None)
        # source untouched
        self.assertTrue((root / "README.md").is_file())

    def test_build_refuses_unmarked_existing_directory(self) -> None:
        root = _fixture_root(self.tmp)
        out = self.tmp / "out"
        out.mkdir()
        _write(out / "user-file.txt", "user data\n")
        with self.assertRaises(ValueError):
            hd.cmd_build(root, out, None)
        self.assertEqual(
            (out / "user-file.txt").read_text(encoding="utf-8"), "user data\n"
        )

    def test_failed_build_preserves_previous_output(self) -> None:
        root = _fixture_root(self.tmp)
        overlay = root / "overlays" / "java"
        _write(
            overlay / "harness-demo.overlay.md",
            '<!-- @append-after section:"Workflow 概要" -->\n### Java 增量编译\n',
        )
        out = self.tmp / "out"
        hd.cmd_build(root, out, "java")  # valid first build
        old_hashes = hd.collect_files(out)

        # break the overlay anchor -> second build must fail
        (overlay / "harness-demo.overlay.md").write_text(
            '<!-- @override section:"不存在的章节" -->\n## X\n', encoding="utf-8"
        )
        with self.assertRaises((KeyError, ValueError)):
            hd.cmd_build(root, out, "java")

        new_hashes = hd.collect_files(out)
        self.assertEqual(new_hashes, old_hashes, "failed build must preserve previous output")

    def test_two_builds_are_byte_identical(self) -> None:
        root = _fixture_root(self.tmp)
        out1 = self.tmp / "out1"
        out2 = self.tmp / "out2"
        hd.cmd_build(root, out1, None)
        hd.cmd_build(root, out2, None)
        self.assertEqual(hd.collect_files(out1), hd.collect_files(out2))

    def test_runtime_build_excludes_tests_and_debug_artifacts(self) -> None:
        root = _fixture_root(self.tmp)
        _write(root / "scripts" / "harness_x.py", "# x\n")
        _write(root / "scripts" / "tests" / "test_x.py", "# test\n")
        _write(root / "scripts" / "tests" / "_last_run.txt", "run\n")
        _write(root / "scripts" / "tests" / "_same_proc_pid.txt", "pid\n")
        # a stray .pyc to prove exclusion
        _write(root / "harness-demo" / "junk.pyc", "bytecode\n")
        out = self.tmp / "out"
        hd.cmd_build(root, out, None)
        self.assertTrue((out / "scripts" / "harness_x.py").is_file())
        self.assertFalse((out / "scripts" / "tests").exists(), "scripts/tests must be excluded")
        for p in out.rglob("*"):
            if not p.is_file():
                continue
            rel = p.relative_to(out).as_posix()
            self.assertFalse(rel.startswith("scripts/tests"), f"tests leaked: {rel}")
            self.assertFalse(p.name == "_last_run.txt", f"debug artifact leaked: {rel}")
            self.assertFalse(p.name.startswith("_same_proc"), f"debug artifact leaked: {rel}")
            self.assertFalse(rel.endswith(".pyc"), f"pyc leaked: {rel}")

    def test_duplicate_section_id_fails(self) -> None:
        root = _fixture_root(self.tmp)
        (root / "harness-demo" / "SKILL.md").write_text(
            "---\nname: harness-demo\n---\n\n# Demo\n\n"
            "<!-- @section-id submit.workflow -->\n## Workflow\n\ncontent A\n\n"
            "<!-- @section-id submit.workflow -->\n## Other\n\ncontent B\n",
            encoding="utf-8",
        )
        with self.assertRaises(ValueError) as cm:
            hd.cmd_build(root, self.tmp / "out", None)
        self.assertIn("submit.workflow", str(cm.exception))


if __name__ == "__main__":
    unittest.main(verbosity=2)
