#!/usr/bin/env python3
"""Unittests for harness_deploy.py (v1.0 单投影 surface 模型）。

v1.0 起：cmd_build(skills_root, out_dir, surface)，surface ∈ {"codex","codebuddy"}；
overlay/profile/adapters 矩阵与 cmd_install 均已退役。
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock


SCRIPTS_DIR = Path(__file__).resolve().parents[1]
SKILLS_ROOT = SCRIPTS_DIR.parent
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

import harness_deploy as hd  # noqa: E402


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _fixture_root(tmp: Path) -> Path:
    root = tmp / "core"
    _write(
        root / "shared" / "p0-trust.md",
        "## P0 执行可信度规则\n\n- rule one\n",
    )
    _write(
        root / "harness-demo" / "SKILL.md",
        """---
name: harness-demo
description: demo skill
---
# Demo

## Workflow 概要

core workflow line

## 构建验证

old build section

<!-- @include shared/p0-trust.md -->
> 片段：[[shared/p0-trust.md|p0-trust]]
""",
    )
    _write(root / "README.md", "# core\n")
    return root


class IncludeExpansionTests(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = Path(tempfile.mkdtemp(prefix="deploy-include-"))
        self.root = _fixture_root(self.tmp)

    def tearDown(self) -> None:
        shutil.rmtree(self.tmp, ignore_errors=True)

    def test_build_expands_includes_and_removes_placeholders(self) -> None:
        out = self.tmp / "out"
        result = hd.cmd_build(self.root, out, "codex")
        self.assertTrue(result["ok"])
        skill = (out / "harness-demo" / "SKILL.md").read_text(encoding="utf-8")
        self.assertIn("rule one", skill)
        self.assertNotIn("@include shared/", skill)
        self.assertNotIn("片段：[[shared/", skill)
        self.assertIn("generated by harness_deploy.py", skill)
        self.assertIn("agent=codex", skill)

    def test_unknown_surface_rejected(self) -> None:
        with self.assertRaises(ValueError) as cm:
            hd.cmd_build(self.root, self.tmp / "bad", "java")
        self.assertIn("unknown surface", str(cm.exception))


class BuildCliContractTests(unittest.TestCase):
    def test_build_parser_subcommands(self) -> None:
        """v1.0 deploy CLI 只保留 build/validate-manifest/generate-manifest/
        verify-installed；install/diff 子命令不得回流。"""
        parser = hd.build_parser()
        group = getattr(parser, "_subparsers", None)
        actions = getattr(group, "_group_actions", []) if group is not None else []
        sub_action = actions[0] if actions else None
        self.assertIsNotNone(sub_action)
        choices = set(getattr(sub_action, "choices", {}).keys())
        self.assertEqual(
            choices,
            {"build", "validate-manifest", "generate-manifest", "verify-installed"},
        )
        self.assertFalse(hasattr(hd, "cmd_diff"), "cmd_diff must stay removed")
        self.assertFalse(hasattr(hd, "cmd_install"), "cmd_install must stay removed")

    def test_core_hash_covers_runtime_reference_files(self) -> None:
        tmp = Path(tempfile.mkdtemp(prefix="deploy-hashref-"))
        try:
            root = _fixture_root(tmp)
            _write(root / "harness-demo" / "reference.md", "first\n")
            first = hd.core_content_hash(root)
            _write(root / "harness-demo" / "reference.md", "second\n")
            self.assertNotEqual(first, hd.core_content_hash(root))
        finally:
            shutil.rmtree(tmp, ignore_errors=True)


class RealSkillsRootBuildTests(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = Path(tempfile.mkdtemp(prefix="deploy-real-"))
        self.out = self.tmp / "out"

    def tearDown(self) -> None:
        shutil.rmtree(self.tmp, ignore_errors=True)

    @unittest.skipUnless(SKILLS_ROOT.is_dir(), "skills root missing")
    def test_build_generic_skills_root(self) -> None:
        for surface in hd.PROJECTION_SURFACES:
            out = self.tmp / f"out-{surface}"
            result = hd.cmd_build(SKILLS_ROOT, out, surface)
            self.assertTrue(result["ok"])
            self.assertEqual(result["agent"], surface)
            self.assertGreaterEqual(len(result["processedSkills"]), 10)
            for rel in result["processedSkills"]:
                body = (out / rel).read_text(encoding="utf-8")
                self.assertNotIn("@include shared/", body)

    @unittest.skipUnless(SKILLS_ROOT.is_dir(), "skills root missing")
    def test_surfaces_build_identical_content_except_marker(self) -> None:
        out_codex = self.tmp / "out-codex"
        out_cb = self.tmp / "out-cb"
        hd.cmd_build(SKILLS_ROOT, out_codex, "codex")
        hd.cmd_build(SKILLS_ROOT, out_cb, "codebuddy")
        codex_files = hd.collect_files(out_codex)
        cb_files = hd.collect_files(out_cb)
        self.assertEqual(set(codex_files), set(cb_files))
        header_marker = b"generated by harness_deploy.py"
        for rel in codex_files:
            if rel.endswith(".harness-build.json"):
                continue
            # 合成 header 行内嵌 agent=<surface>，属预期差异，剔除后比对。
            a_bytes = (out_codex / rel).read_bytes()
            b_bytes = (out_cb / rel).read_bytes()
            a_lines = [l for l in a_bytes.split(b"\n") if header_marker not in l]
            b_lines = [l for l in b_bytes.split(b"\n") if header_marker not in l]
            self.assertEqual(a_lines, b_lines, f"surface content drift in {rel}")


class DeploySafetyReproTests(unittest.TestCase):
    """Task 5 (REMEDIATION-DESIGN §7): path safety, atomic staging swap,
    reproducible builds, runtime allowlist, section-id anchors."""

    def setUp(self) -> None:
        self.tmp = Path(tempfile.mkdtemp(prefix="deploy-safety-"))

    def tearDown(self) -> None:
        shutil.rmtree(self.tmp, ignore_errors=True)

    def test_build_refuses_out_equal_to_source(self) -> None:
        root = _fixture_root(self.tmp)
        with self.assertRaises(ValueError):
            hd.cmd_build(root, root, "codex")
        # source untouched
        self.assertTrue((root / "README.md").is_file())

    def test_build_refuses_unmarked_existing_directory(self) -> None:
        root = _fixture_root(self.tmp)
        out = self.tmp / "out"
        out.mkdir()
        _write(out / "user-file.txt", "user data\n")
        with self.assertRaises(ValueError):
            hd.cmd_build(root, out, "codex")
        self.assertEqual(
            (out / "user-file.txt").read_text(encoding="utf-8"), "user data\n"
        )

    def test_failed_build_preserves_previous_output(self) -> None:
        root = _fixture_root(self.tmp)
        out = self.tmp / "out"
        hd.cmd_build(root, out, "codex")  # valid first build
        old_hashes = hd.collect_files(out)

        # break the bundle: unresolved include placeholder must fail the build
        _write(
            root / "harness-broken" / "SKILL.md",
            "---\nname: harness-broken\n---\n# Broken\n\n"
            "<!-- @include shared/does-not-exist.md -->\n",
        )
        with self.assertRaises((KeyError, ValueError, RuntimeError, FileNotFoundError)):
            hd.cmd_build(root, out, "codex")

        new_hashes = hd.collect_files(out)
        self.assertEqual(new_hashes, old_hashes, "failed build must preserve previous output")

    def test_atomic_replace_retries_transient_permission_error(self) -> None:
        source = self.tmp / "source"
        target = self.tmp / "target"
        source.mkdir()
        _write(source / "marker.txt", "new\n")
        real_replace = os.replace
        attempts = 0

        def flaky_replace(src: object, dst: object) -> None:
            nonlocal attempts
            attempts += 1
            if attempts < 3:
                raise PermissionError("transient scanner lock")
            real_replace(src, dst)

        with (
            mock.patch.object(hd.os, "replace", side_effect=flaky_replace),
            mock.patch.object(hd.time, "sleep") as sleep,
        ):
            hd.replace_with_retry(source, target)

        self.assertEqual(attempts, 3)
        self.assertEqual(sleep.call_count, 2)
        self.assertEqual((target / "marker.txt").read_text(encoding="utf-8"), "new\n")

    def test_atomic_replace_stops_after_bounded_retries(self) -> None:
        source = self.tmp / "source"
        target = self.tmp / "target"
        source.mkdir()
        with (
            mock.patch.object(
                hd.os, "replace", side_effect=PermissionError("persistent lock")
            ) as replace,
            mock.patch.object(hd.time, "sleep") as sleep,
        ):
            with self.assertRaises(PermissionError):
                hd.replace_with_retry(source, target)

        self.assertEqual(
            replace.call_count, len(hd._REPLACE_RETRY_DELAYS_SECONDS) + 1
        )
        self.assertEqual(sleep.call_count, len(hd._REPLACE_RETRY_DELAYS_SECONDS))

    def test_two_builds_are_byte_identical(self) -> None:
        root = _fixture_root(self.tmp)
        out1 = self.tmp / "out1"
        out2 = self.tmp / "out2"
        hd.cmd_build(root, out1, "codex")
        hd.cmd_build(root, out2, "codex")
        self.assertEqual(hd.collect_files(out1), hd.collect_files(out2))

    def test_generated_skill_uses_lf_newlines(self) -> None:
        root = _fixture_root(self.tmp)
        out = self.tmp / "out"
        hd.cmd_build(root, out, "codex")
        self.assertNotIn(b"\r\n", (out / "harness-demo" / "SKILL.md").read_bytes())

    def test_runtime_build_excludes_tests_and_debug_artifacts(self) -> None:
        root = _fixture_root(self.tmp)
        _write(root / "scripts" / "harness_x.py", "# x\n")
        _write(root / "scripts" / "tests" / "test_x.py", "# test\n")
        _write(root / "scripts" / "tests" / "_last_run.txt", "run\n")
        _write(root / "scripts" / "tests" / "_same_proc_pid.txt", "pid\n")
        # a stray .pyc to prove exclusion
        _write(root / "harness-demo" / "junk.pyc", "bytecode\n")
        out = self.tmp / "out"
        hd.cmd_build(root, out, "codex")
        self.assertTrue((out / "scripts" / "harness_x.py").is_file())
        self.assertFalse((out / "scripts" / "tests").exists(), "scripts/tests must be excluded")
        for p in out.rglob("*"):
            if not p.is_file():
                continue
            rel = p.relative_to(out).as_posix()
            self.assertFalse(rel.startswith("scripts/tests"), f"tests leaked: {rel}")
            self.assertFalse(p.name == "_last_run.txt", f"debug artifact leaked: {rel}")
            self.assertFalse(p.name.startswith("_same_proc"), f"debug artifact leaked: {rel}")
            self.assertFalse(rel.endswith(".pyc"), f"pyc leaked: {rel}")

    def test_runtime_build_excludes_nested_skill_tests_and_fixtures(self) -> None:
        root = _fixture_root(self.tmp)
        _write(root / "harness-demo" / "tests" / "test_demo.py", "# test\n")
        _write(
            root / "harness-demo" / "tests" / "fixtures" / "sample.json",
            "{}\n",
        )
        out = self.tmp / "out"
        hd.cmd_build(root, out, "codex")
        self.assertFalse((out / "harness-demo" / "tests").exists())

    def test_duplicate_section_id_fails(self) -> None:
        root = _fixture_root(self.tmp)
        (root / "harness-demo" / "SKILL.md").write_text(
            "---\nname: harness-demo\n---\n\n# Demo\n\n"
            "<!-- @section-id submit.workflow -->\n## Workflow\n\ncontent A\n\n"
            "<!-- @section-id submit.workflow -->\n## Other\n\ncontent B\n",
            encoding="utf-8",
        )
        with self.assertRaises(ValueError) as cm:
            hd.cmd_build(root, self.tmp / "out", "codex")
        self.assertIn("submit.workflow", str(cm.exception))


class ValidateManifestTests(unittest.TestCase):
    """UT-030 + API-012: manifest validator — declared set vs actual managed set,
    missing and extra both fail (design §3.8 要点2)."""

    def setUp(self) -> None:
        self.tmp = Path(tempfile.mkdtemp(prefix="deploy-validate-"))

    def tearDown(self) -> None:
        shutil.rmtree(self.tmp, ignore_errors=True)

    def _bundle(self, files: dict[str, str]) -> Path:
        bundle = self.tmp / "bundle"
        for rel, content in files.items():
            _write(bundle / rel, content)
        return bundle

    def _manifest(self, bundle: Path, entries: list[tuple[str, str | None]]) -> list[dict]:
        items: list[dict] = []
        for path, sha in entries:
            if sha is None:
                sha = hd.sha256_file(bundle / Path(path))
            items.append({"path": path, "sha256": sha})
        return items

    def test_validate_manifest_ok_when_consistent(self) -> None:
        bundle = self._bundle({"harness-demo/SKILL.md": "x\n"})
        result = hd.cmd_validate_manifest(
            bundle, self._manifest(bundle, [("harness-demo/SKILL.md", None)])
        )
        self.assertTrue(result["ok"])
        self.assertEqual(result["missing"], [])
        self.assertEqual(result["extra"], [])
        self.assertEqual(result["hashMismatch"], [])

    def test_validate_manifest_detects_extra(self) -> None:
        bundle = self._bundle({"harness-demo/SKILL.md": "x\n", "stray.txt": "extra\n"})
        result = hd.cmd_validate_manifest(
            bundle, self._manifest(bundle, [("harness-demo/SKILL.md", None)])
        )
        self.assertFalse(result["ok"])
        self.assertIn("stray.txt", result["extra"])

    def test_validate_manifest_detects_missing(self) -> None:
        bundle = self._bundle({"harness-demo/SKILL.md": "x\n"})
        result = hd.cmd_validate_manifest(
            bundle,
            self._manifest(
                bundle,
                [("harness-demo/SKILL.md", None), ("harness-extra/SKILL.md", "0" * 64)],
            ),
        )
        self.assertFalse(result["ok"])
        self.assertIn("harness-extra/SKILL.md", result["missing"])

    def test_validate_manifest_detects_hash_mismatch(self) -> None:
        bundle = self._bundle({"harness-demo/SKILL.md": "x\n"})
        result = hd.cmd_validate_manifest(
            bundle, [{"path": "harness-demo/SKILL.md", "sha256": "0" * 64}]
        )
        self.assertFalse(result["ok"])
        self.assertIn("harness-demo/SKILL.md", result["hashMismatch"])


class CoreContentHashTests(unittest.TestCase):
    """v1.0 core_content_hash：对构建输入工作树字节做确定性 SHA-256，
    与机器路径/时间无关；内容变化必须反映到 hash。"""

    def setUp(self) -> None:
        self.tmp = Path(tempfile.mkdtemp(prefix="deploy-core-"))
        self.root = self.tmp / "core"
        _write(self.root / "shared" / "p0.md", "shared\n")
        _write(self.root / "harness-demo" / "SKILL.md", "# demo\nline two\n")

    def tearDown(self) -> None:
        shutil.rmtree(self.tmp, ignore_errors=True)

    def test_tracked_content_change_does_change_core_hash(self) -> None:
        first = hd.core_content_hash(self.root)
        _write(self.root / "harness-demo" / "SKILL.md", "# demo\nchanged content\n")
        second = hd.core_content_hash(self.root)
        self.assertNotEqual(first, second)

    def test_hash_is_deterministic_for_identical_inputs(self) -> None:
        self.assertEqual(hd.core_content_hash(self.root), hd.core_content_hash(self.root))

    def test_git_metadata_does_not_affect_hash(self) -> None:
        without_git = hd.core_content_hash(self.root)
        subprocess.run(["git", "init", "-q"], cwd=self.tmp, check=True)
        subprocess.run(["git", "add", "."], cwd=self.tmp, check=True)
        self.assertEqual(without_git, hd.core_content_hash(self.root))


if __name__ == "__main__":
    unittest.main(verbosity=2)
