#!/usr/bin/env python3
"""Unittests for harness_deploy.py (P2-1)."""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


SCRIPTS_DIR = Path(__file__).resolve().parents[1]
SKILLS_ROOT = SCRIPTS_DIR.parent
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

import harness_deploy as hd  # noqa: E402


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _fixture_root(tmp: Path) -> Path:
    root = tmp / "core"
    _write(
        root / "shared" / "p0-trust.md",
        "## P0 执行可信度规则\n\n- rule one\n",
    )
    _write(
        root / "harness-demo" / "SKILL.md",
        """---
name: harness-demo
---
# Demo

## Workflow 概要

core workflow line

## 构建验证

old build section

<!-- @include shared/p0-trust.md -->
> 片段：[[shared/p0-trust.md|p0-trust]]
""",
    )
    _write(root / "README.md", "# core\n")
    return root


class IncludeExpansionTests(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = Path(tempfile.mkdtemp(prefix="deploy-include-"))
        self.root = _fixture_root(self.tmp)

    def tearDown(self) -> None:
        shutil.rmtree(self.tmp, ignore_errors=True)

    def test_build_expands_includes_and_removes_placeholders(self) -> None:
        out = self.tmp / "out"
        result = hd.cmd_build(self.root, out, None)
        self.assertTrue(result["ok"])
        skill = (out / "harness-demo" / "SKILL.md").read_text(encoding="utf-8")
        self.assertIn("rule one", skill)
        self.assertNotIn("@include shared/", skill)
        self.assertNotIn("片段：[[shared/", skill)
        self.assertIn("generated by harness_deploy.py", skill)


class OverlayAnchorTests(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = Path(tempfile.mkdtemp(prefix="deploy-overlay-"))
        self.root = _fixture_root(self.tmp)
        overlay = self.root / "overlays" / "java"
        _write(
            overlay / "harness-demo.overlay.md",
            """<!-- @override section:"构建验证" -->
## 构建验证

mvn compile -pl demo-module

<!-- @append-after section:"Workflow 概要" -->
### Java 增量编译

read build-profile.json
""",
        )
        _write(
            overlay / "harness-extra" / "SKILL.md",
            """---
name: harness-extra
---
# Extra Java Skill
""",
        )

    def tearDown(self) -> None:
        shutil.rmtree(self.tmp, ignore_errors=True)

    def test_build_applies_override_and_append(self) -> None:
        out = self.tmp / "out"
        result = hd.cmd_build(self.root, out, "java")
        skill = (out / "harness-demo" / "SKILL.md").read_text(encoding="utf-8")
        self.assertIn("mvn compile -pl demo-module", skill)
        self.assertNotIn("old build section", skill)
        self.assertIn("### Java 增量编译", skill)
        self.assertTrue((out / "harness-extra" / "SKILL.md").is_file())

    def test_build_fails_on_missing_anchor(self) -> None:
        bad = self.root / "overlays" / "java" / "harness-demo.overlay.md"
        bad.write_text(
            '<!-- @override section:"不存在的章节" -->\n## X\n',
            encoding="utf-8",
        )
        with self.assertRaises(KeyError):
            hd.cmd_build(self.root, self.tmp / "bad-out", "java")


class InstallDiffTests(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = Path(tempfile.mkdtemp(prefix="deploy-install-"))
        self.root = _fixture_root(self.tmp)
        self.out = self.tmp / "build-out"
        hd.cmd_build(self.root, self.out, None)
        self.project = self.tmp / "project"
        self.project.mkdir()

    def tearDown(self) -> None:
        shutil.rmtree(self.tmp, ignore_errors=True)

    def test_install_creates_backup(self) -> None:
        target = self.project / ".claude" / "skills"
        target.mkdir(parents=True)
        _write(target / "old.txt", "old\n")
        result = hd.cmd_install(self.out, self.project, target)
        self.assertTrue(result["ok"])
        self.assertIsNotNone(result["backup"])
        self.assertTrue(Path(result["backup"]).is_dir())
        self.assertTrue((target / "harness-demo" / "SKILL.md").is_file())

    def test_diff_subcommand_removed(self) -> None:
        """RET-35/task 13：raw build vs installed 字节比较已删除——post-adaptation
        projection 才是正式比较入口；deploy CLI 不得再暴露 diff。"""
        parser = hd.build_parser()
        group = getattr(parser, "_subparsers", None)
        actions = getattr(group, "_group_actions", []) if group is not None else []
        sub_action = actions[0] if actions else None
        self.assertIsNotNone(sub_action)
        choices = set(getattr(sub_action, "choices", {}).keys())
        self.assertNotIn("diff", choices, "diff subcommand must be removed")
        self.assertFalse(hasattr(hd, "cmd_diff"), "cmd_diff must be removed")

    def test_core_hash_covers_runtime_reference_files(self) -> None:
        _write(self.root / "harness-demo" / "reference.md", "first\n")
        first = hd.core_content_hash(self.root, None)
        _write(self.root / "harness-demo" / "reference.md", "second\n")
        self.assertNotEqual(first, hd.core_content_hash(self.root, None))

    def test_install_rejects_unmarked_source_without_touching_target(self) -> None:
        target = self.project / ".claude" / "skills"
        _write(target / "old.txt", "old\n")
        unmarked = self.tmp / "unmarked"
        _write(unmarked / "file.txt", "bad\n")
        with self.assertRaises(ValueError):
            hd.cmd_install(unmarked, self.project, target)
        self.assertEqual((target / "old.txt").read_text(encoding="utf-8"), "old\n")


class RealSkillsRootBuildTests(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = Path(tempfile.mkdtemp(prefix="deploy-real-"))
        self.out = self.tmp / "out"

    def tearDown(self) -> None:
        shutil.rmtree(self.tmp, ignore_errors=True)

    @unittest.skipUnless(SKILLS_ROOT.is_dir(), "skills root missing")
    def test_build_generic_skills_root(self) -> None:
        result = hd.cmd_build(SKILLS_ROOT, self.out, None)
        self.assertTrue(result["ok"])
        self.assertGreaterEqual(len(result["processedSkills"]), 10)
        for rel in result["processedSkills"]:
            body = (self.out / rel).read_text(encoding="utf-8")
            self.assertNotIn("@include shared/", body)


class DeploySafetyReproTests(unittest.TestCase):
    """Task 5 (REMEDIATION-DESIGN §7): path safety, atomic staging swap,
    reproducible builds, runtime allowlist, section-id anchors."""

    def setUp(self) -> None:
        self.tmp = Path(tempfile.mkdtemp(prefix="deploy-safety-"))

    def tearDown(self) -> None:
        shutil.rmtree(self.tmp, ignore_errors=True)

    def test_build_refuses_out_equal_to_source(self) -> None:
        root = _fixture_root(self.tmp)
        with self.assertRaises(ValueError):
            hd.cmd_build(root, root, None)
        # source untouched
        self.assertTrue((root / "README.md").is_file())

    def test_build_refuses_unmarked_existing_directory(self) -> None:
        root = _fixture_root(self.tmp)
        out = self.tmp / "out"
        out.mkdir()
        _write(out / "user-file.txt", "user data\n")
        with self.assertRaises(ValueError):
            hd.cmd_build(root, out, None)
        self.assertEqual(
            (out / "user-file.txt").read_text(encoding="utf-8"), "user data\n"
        )

    def test_failed_build_preserves_previous_output(self) -> None:
        root = _fixture_root(self.tmp)
        overlay = root / "overlays" / "java"
        _write(
            overlay / "harness-demo.overlay.md",
            '<!-- @append-after section:"Workflow 概要" -->\n### Java 增量编译\n',
        )
        out = self.tmp / "out"
        hd.cmd_build(root, out, "java")  # valid first build
        old_hashes = hd.collect_files(out)

        # break the overlay anchor -> second build must fail
        (overlay / "harness-demo.overlay.md").write_text(
            '<!-- @override section:"不存在的章节" -->\n## X\n', encoding="utf-8"
        )
        with self.assertRaises((KeyError, ValueError)):
            hd.cmd_build(root, out, "java")

        new_hashes = hd.collect_files(out)
        self.assertEqual(new_hashes, old_hashes, "failed build must preserve previous output")

    def test_two_builds_are_byte_identical(self) -> None:
        root = _fixture_root(self.tmp)
        out1 = self.tmp / "out1"
        out2 = self.tmp / "out2"
        hd.cmd_build(root, out1, None)
        hd.cmd_build(root, out2, None)
        self.assertEqual(hd.collect_files(out1), hd.collect_files(out2))

    def test_generated_skill_uses_lf_newlines(self) -> None:
        root = _fixture_root(self.tmp)
        out = self.tmp / "out"
        hd.cmd_build(root, out, None)
        self.assertNotIn(b"\r\n", (out / "harness-demo" / "SKILL.md").read_bytes())

    def test_runtime_build_excludes_tests_and_debug_artifacts(self) -> None:
        root = _fixture_root(self.tmp)
        _write(root / "scripts" / "harness_x.py", "# x\n")
        _write(root / "scripts" / "tests" / "test_x.py", "# test\n")
        _write(root / "scripts" / "tests" / "_last_run.txt", "run\n")
        _write(root / "scripts" / "tests" / "_same_proc_pid.txt", "pid\n")
        # a stray .pyc to prove exclusion
        _write(root / "harness-demo" / "junk.pyc", "bytecode\n")
        out = self.tmp / "out"
        hd.cmd_build(root, out, None)
        self.assertTrue((out / "scripts" / "harness_x.py").is_file())
        self.assertFalse((out / "scripts" / "tests").exists(), "scripts/tests must be excluded")
        for p in out.rglob("*"):
            if not p.is_file():
                continue
            rel = p.relative_to(out).as_posix()
            self.assertFalse(rel.startswith("scripts/tests"), f"tests leaked: {rel}")
            self.assertFalse(p.name == "_last_run.txt", f"debug artifact leaked: {rel}")
            self.assertFalse(p.name.startswith("_same_proc"), f"debug artifact leaked: {rel}")
            self.assertFalse(rel.endswith(".pyc"), f"pyc leaked: {rel}")

    def test_runtime_build_excludes_nested_skill_tests_and_fixtures(self) -> None:
        root = _fixture_root(self.tmp)
        _write(root / "harness-demo" / "tests" / "test_demo.py", "# test\n")
        _write(
            root / "harness-demo" / "tests" / "fixtures" / "sample.json",
            "{}\n",
        )
        out = self.tmp / "out"
        hd.cmd_build(root, out, None)
        self.assertFalse((out / "harness-demo" / "tests").exists())

    def test_duplicate_section_id_fails(self) -> None:
        root = _fixture_root(self.tmp)
        (root / "harness-demo" / "SKILL.md").write_text(
            "---\nname: harness-demo\n---\n\n# Demo\n\n"
            "<!-- @section-id submit.workflow -->\n## Workflow\n\ncontent A\n\n"
            "<!-- @section-id submit.workflow -->\n## Other\n\ncontent B\n",
            encoding="utf-8",
        )
        with self.assertRaises(ValueError) as cm:
            hd.cmd_build(root, self.tmp / "out", None)
        self.assertIn("submit.workflow", str(cm.exception))


class AgentAdapterBuildTests(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = Path(tempfile.mkdtemp(prefix="deploy-agent-"))
        self.root = _fixture_root(self.tmp)
        _write(
            self.root / "agents" / "demo-agent.md",
            "---\nname: demo-agent\ndescription: demo\n---\n# Demo Agent\n",
        )
        _write(
            self.root / "adapters" / "codex" / "skill-overlays" / "harness-demo.overlay.md",
            '<!-- @override section:"构建验证" -->\n## 构建验证\n\ncodex adapted build section\n',
        )
        _write(
            self.root / "adapters" / "codebuddy" / "agents" / "demo-agent.md",
            "---\nname: demo-agent\ndescription: codebuddy override\n---\n# CB\n",
        )
        # Ensure adapters/ never ends up in output even if present as top-level content.
        _write(self.root / "adapters" / "codex" / "README.md", "adapter docs\n")

    def tearDown(self) -> None:
        shutil.rmtree(self.tmp, ignore_errors=True)

    def test_agent_flag_applies_adapter_overlay(self) -> None:
        out = self.tmp / "out-codex"
        result = hd.cmd_build(self.root, out, None, agent="codex")
        self.assertTrue(result["ok"])
        skill = (out / "harness-demo" / "SKILL.md").read_text(encoding="utf-8")
        self.assertIn("codex adapted build section", skill)
        self.assertNotIn("old build section", skill)
        self.assertIn("agent=codex", skill)

    def test_agents_dir_copied_only_for_claude_and_codebuddy(self) -> None:
        for agent, expect_agents in (
            ("claude-code", True),
            ("codebuddy", True),
            ("codex", False),
            ("cursor", False),
        ):
            out = self.tmp / f"out-{agent}"
            hd.cmd_build(self.root, out, None, agent=agent)
            self.assertEqual(
                (out / "agents").is_dir(),
                expect_agents,
                f"agents/ presence mismatch for {agent}",
            )

    def test_adapters_dir_never_copied_into_bundle(self) -> None:
        for agent in hd.HARNESS_AGENTS:
            out = self.tmp / f"out-no-adapters-{agent}"
            hd.cmd_build(self.root, out, None, agent=agent)
            self.assertFalse((out / "adapters").exists(), f"adapters leaked for {agent}")

    def test_missing_agent_defaults_claude_with_warning(self) -> None:
        out = self.tmp / "out-default"
        import io
        from contextlib import redirect_stderr

        buf = io.StringIO()
        with redirect_stderr(buf):
            result = hd.cmd_build(self.root, out, None, agent=None)
        self.assertTrue(result["ok"])
        self.assertEqual(result["agent"], "claude-code")
        self.assertRegex(buf.getvalue(), r"(?i)deprecat")
        self.assertTrue((out / "agents" / "demo-agent.md").is_file())

    def test_unknown_agent_rejected(self) -> None:
        with self.assertRaises(ValueError) as cm:
            hd.cmd_build(self.root, self.tmp / "bad", None, agent="gpt")
        self.assertIn("unknown agent", str(cm.exception))

    def test_codebuddy_adapter_agents_override_canonical(self) -> None:
        out = self.tmp / "out-cb"
        hd.cmd_build(self.root, out, None, agent="codebuddy")
        body = (out / "agents" / "demo-agent.md").read_text(encoding="utf-8")
        self.assertIn("codebuddy override", body)


class InstallConservativeTests(unittest.TestCase):
    """UT-032 + COM-005: conservative install removes removed managed files
    but preserves user-owned files (design §3.8 要点4)."""

    def setUp(self) -> None:
        self.tmp = Path(tempfile.mkdtemp(prefix="deploy-conservative-"))
        self.project = self.tmp / "project"
        self.project.mkdir()

    def tearDown(self) -> None:
        shutil.rmtree(self.tmp, ignore_errors=True)

    def test_install_removes_removed_managed_agent_keeps_user_agent(self) -> None:
        root_v1 = _fixture_root(self.tmp / "src-v1")
        _write(root_v1 / "agents" / "managed-a.md",
               "---\nname: managed-a\ndescription: a\n---\n# A\n")
        _write(root_v1 / "agents" / "managed-b.md",
               "---\nname: managed-b\ndescription: b\n---\n# B\n")
        out_v1 = self.tmp / "out-v1"
        hd.cmd_build(root_v1, out_v1, None, agent="claude-code")
        target = self.project / ".claude" / "skills"
        hd.cmd_install(out_v1, self.project, target)
        agents_dest = self.project / ".claude" / "agents"
        _write(agents_dest / "user-c.md",
               "---\nname: user-c\ndescription: user\n---\n# C\n")

        root_v2 = _fixture_root(self.tmp / "src-v2")
        _write(root_v2 / "agents" / "managed-b.md",
               "---\nname: managed-b\ndescription: b2\n---\n# B2\n")
        out_v2 = self.tmp / "out-v2"
        hd.cmd_build(root_v2, out_v2, None, agent="claude-code")
        hd.cmd_install(out_v2, self.project, target)

        self.assertFalse((agents_dest / "managed-a.md").exists(),
                         "removed managed agent must be deleted")
        self.assertEqual(
            (agents_dest / "managed-b.md").read_text(encoding="utf-8"),
            "---\nname: managed-b\ndescription: b2\n---\n# B2\n",
        )
        self.assertTrue((agents_dest / "user-c.md").exists(),
                        "user agent must be preserved")

    def test_install_removes_removed_managed_skill_keeps_user_skill(self) -> None:
        root_v1 = _fixture_root(self.tmp / "core-v1")
        _write(root_v1 / "harness-extra" / "SKILL.md",
               "---\nname: harness-extra\n---\n# Extra\n")
        out_v1 = self.tmp / "out-c1"
        hd.cmd_build(root_v1, out_v1, None)
        target = self.project / ".claude" / "skills"
        hd.cmd_install(out_v1, self.project, target)
        self.assertTrue((target / "harness-extra" / "SKILL.md").is_file())
        _write(target / "user-skill" / "SKILL.md", "# user\n")

        root_v2 = _fixture_root(self.tmp / "core-v2")
        out_v2 = self.tmp / "out-c2"
        hd.cmd_build(root_v2, out_v2, None)
        hd.cmd_install(out_v2, self.project, target)

        self.assertFalse((target / "harness-extra").exists(),
                         "removed managed skill must be deleted")
        self.assertTrue((target / "user-skill" / "SKILL.md").is_file(),
                        "user skill must be preserved")
        self.assertTrue((target / "harness-demo" / "SKILL.md").is_file())


class ValidateManifestTests(unittest.TestCase):
    """UT-030 + API-012: manifest validator — declared set vs actual managed set,
    missing and extra both fail (design §3.8 要点2)."""

    def setUp(self) -> None:
        self.tmp = Path(tempfile.mkdtemp(prefix="deploy-validate-"))

    def tearDown(self) -> None:
        shutil.rmtree(self.tmp, ignore_errors=True)

    def _bundle(self, files: dict[str, str]) -> Path:
        bundle = self.tmp / "bundle"
        for rel, content in files.items():
            _write(bundle / rel, content)
        return bundle

    def _manifest(self, bundle: Path, entries: list[tuple[str, str | None]]) -> list[dict]:
        items: list[dict] = []
        for path, sha in entries:
            if sha is None:
                sha = hd.sha256_file(bundle / Path(path))
            items.append({"path": path, "sha256": sha})
        return items

    def test_validate_manifest_ok_when_consistent(self) -> None:
        bundle = self._bundle({"harness-demo/SKILL.md": "x\n"})
        result = hd.cmd_validate_manifest(
            bundle, self._manifest(bundle, [("harness-demo/SKILL.md", None)])
        )
        self.assertTrue(result["ok"])
        self.assertEqual(result["missing"], [])
        self.assertEqual(result["extra"], [])
        self.assertEqual(result["hashMismatch"], [])

    def test_validate_manifest_detects_extra(self) -> None:
        bundle = self._bundle({"harness-demo/SKILL.md": "x\n", "stray.txt": "extra\n"})
        result = hd.cmd_validate_manifest(
            bundle, self._manifest(bundle, [("harness-demo/SKILL.md", None)])
        )
        self.assertFalse(result["ok"])
        self.assertIn("stray.txt", result["extra"])

    def test_validate_manifest_detects_missing(self) -> None:
        bundle = self._bundle({"harness-demo/SKILL.md": "x\n"})
        result = hd.cmd_validate_manifest(
            bundle,
            self._manifest(
                bundle,
                [("harness-demo/SKILL.md", None), ("harness-extra/SKILL.md", "0" * 64)],
            ),
        )
        self.assertFalse(result["ok"])
        self.assertIn("harness-extra/SKILL.md", result["missing"])

    def test_validate_manifest_detects_hash_mismatch(self) -> None:
        bundle = self._bundle({"harness-demo/SKILL.md": "x\n"})
        result = hd.cmd_validate_manifest(
            bundle, [{"path": "harness-demo/SKILL.md", "sha256": "0" * 64}]
        )
        self.assertFalse(result["ok"])
        self.assertIn("harness-demo/SKILL.md", result["hashMismatch"])


class CoreContentHashDeterminismTests(unittest.TestCase):
    """core_content_hash must be independent of working-copy CRLF state: it uses
    the git blob sha (CRLF-normalized by .gitattributes) for tracked files, falling
    back to working-tree bytes only for untracked build inputs."""

    def setUp(self) -> None:
        self.tmp = Path(tempfile.mkdtemp(prefix="deploy-core-"))
        self.root = self.tmp / "core"
        _write(self.root / "harness-demo" / "SKILL.md", "# demo\nline two\n")
        # Standalone git repo so _git_repo_root resolves to self.tmp, not the
        # outer worktree. .gitattributes eol=lf normalizes tracked blobs to LF.
        subprocess.run(["git", "init", "-q"], cwd=str(self.tmp), check=True)
        _write(self.tmp / ".gitattributes", "harness/** text eol=lf\n")
        subprocess.run(["git", "add", "-A"], cwd=str(self.tmp), check=True)

    def test_crlf_working_copy_does_not_change_core_hash(self) -> None:
        # Tracked file: index blob is LF (eol=lf). Working copy starts LF.
        lf_hash = hd.core_content_hash(self.root, None)
        # Rewrite working copy as CRLF. The index blob stays LF, so the blob sha
        # (used by core_content_hash) must not change.
        skill = self.root / "harness-demo" / "SKILL.md"
        skill.write_bytes(skill.read_text(encoding="utf-8").replace("\n", "\r\n").encode("utf-8"))
        crlf_hash = hd.core_content_hash(self.root, None)
        self.assertEqual(lf_hash, crlf_hash)

    def test_tracked_content_change_does_change_core_hash(self) -> None:
        first = hd.core_content_hash(self.root, None)
        skill = self.root / "harness-demo" / "SKILL.md"
        _write(skill, "# demo\nchanged content\n")
        subprocess.run(["git", "add", "-A"], cwd=str(self.tmp), check=True)
        second = hd.core_content_hash(self.root, None)
        self.assertNotEqual(first, second)

    def test_untracked_file_falls_back_to_working_copy(self) -> None:
        # Untracked file (not in index): _git_blob_sha None → sha256_file. A content
        # change must still be detected via working-tree bytes.
        ref = self.root / "harness-demo" / "reference.md"
        _write(ref, "first\n")
        first = hd.core_content_hash(self.root, None)
        _write(ref, "second\n")
        second = hd.core_content_hash(self.root, None)
        self.assertNotEqual(first, second)


if __name__ == "__main__":
    unittest.main(verbosity=2)
